# **<span style="color:#ac7940">Matrix Operation</span>**

## Defining a matrix using numpy


In [1]:
import numpy as np

In [15]:
# Defining a matrix
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.size)# cardinality of matrix --> no. of element
print(a.shape) # Order of matrix rxc

[[1 2 3]
 [4 5 6]]
6
(2, 3)


In [17]:
# Checking whether a matrix is a square matrix
def square_matrix(matrix):
    if matrix.shape[0]==matrix.shape[1]:
        print(f"{matrix} is a square matrix")
    else:
        print(f"{matrix} is not a square matrix")

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
square_matrix(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]] is a square matrix


In [19]:
# Transpose of a matrix
a=np.array([[1,2,3,4],[5,6,6,7]])
print(f"Shape of {a} is {a.shape}")
b=a.T # Transpose of a
print(f"Shape of {b} is {b.shape}")

Shape of [[1 2 3 4]
 [5 6 6 7]] is (2, 4)
Shape of [[1 5]
 [2 6]
 [3 6]
 [4 7]] is (4, 2)


## Special types of Square matrix:

In [24]:
# idempotent matrix
def idempotent(matrix):
    if (np.linalg.matrix_power(matrix,2)==matrix).all():
        print(f"Matrix:{matrix} is a idempotent matrix")
idempotent(np.array([[3,3],[-2,-2]]))

Matrix:[[ 3  3]
 [-2 -2]] is a idempotent matrix


In [25]:
# nilpotent matrix
import numpy as np

def is_nilpotent(A, tol=1e-10):
    """
    Check whether matrix A is nilpotent using matrix_power.
    Returns (True, k) if A^k = 0 for some k <= n.
    """

    A = np.array(A, dtype=float)

    # Step 1: must be square
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix must be square")

    n = A.shape[0]

    # Step 2: check A^k for k = 1 to n
    for k in range(1, n + 1):
        Ak = np.linalg.matrix_power(A, k)

        if np.all(np.abs(Ak) < tol):
            return True, k

    return False, None

is_nilpotent(np.array([[0,1,1],[0,0,1],[0,0,0]]))

(True, 3)

In [21]:
a=np.array([[1,2],[3,4]])
print(a@a)
print(np.linalg.matrix_power(a,2))

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [26]:
# Identity matrix:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# Involutory Matrix:
def involutory_matrix(matrix):
    shape=matrix.shape[0]
    if (np.linalg.matrix_power(matrix,2)==np.identity(shape)).all():
        print(f"Matrix {matrix} is involutory matrix")
    else:
        print("not a involutory matrix")

involutory_matrix(np.array([[1,0],[0,-1]]))

Matrix [[ 1  0]
 [ 0 -1]] is involutory matrix


In [28]:
# orthogonal matrix
def orthogonal_matrix(matrix):
    shape=matrix.shape[0]
    if (matrix.T==np.linalg.inv(matrix)).all():
        print(f'Matrix:{matrix} is a orthogonal matrix')
    else:
        print("Matrix is not orthogonal")
orthogonal_matrix(np.array([[0,-1],[1,0]]))

Matrix:[[ 0 -1]
 [ 1  0]] is a orthogonal matrix


In [29]:
# symmetric matrix:
def symmetric_matrix(matrix):
    if (matrix.T==matrix).all():
        print(f"Matrix:{matrix} is symmetric matrix")
    else:
        print("Matrix is not a symmetric matrix")

symmetric_matrix(np.array([[4,2,3],[2,-1.5,-1],[3,-1,1]]))

Matrix:[[ 4.   2.   3. ]
 [ 2.  -1.5 -1. ]
 [ 3.  -1.   1. ]] is symmetric matrix


In [30]:
# skew-symmetric matrix:
def skew_symmetric_matrix(matrix):
    if (matrix.T==-1*matrix).all():
        print(f"Matrix: {matrix} is a skew symmetric matrix")
    else:
        print("Matrix is not skew symmetric")

skew_symmetric_matrix(np.array([[0,1,-2],[-1,0,3],[2,-3,0]]))


Matrix: [[ 0  1 -2]
 [-1  0  3]
 [ 2 -3  0]] is a skew symmetric matrix


In [31]:
print(np.linalg.inv(np.array([[1,0,0],[0,1,0],[0,0,2]])))

[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]]


## Matrix Operations:


In [33]:
# scalar multiplication
matrix=np.array([[1,2,3,4],[3,4,3,2]])
print(1.3*matrix)

[[1.3 2.6 3.9 5.2]
 [3.9 5.2 3.9 2.6]]


In [34]:
# Matrix addition and subtraction:
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(matrix1-matrix2)
print(matrix1+matrix2)

[[-4 -4]
 [-4 -4]]
[[ 6  8]
 [10 12]]


In [35]:
# Matrix Multiplication:
print(matrix1@matrix2)

[[19 22]
 [43 50]]


In [37]:
# Determinant
a=np.array([[1,8,3],[4,5,6],[7,8,9]])
print(np.linalg.det(a))

36.00000000000003


In [ ]:
# Inverse of a matrix:
a=np.array([[1,0,0],[0,1,0],[0,0,2]])
print(np.linalg.inv(a))

[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]]


In [39]:
# Rank of matrix
a=np.array([[1,0,3],[0,1,3],[0,1,3]])
print(np.linalg.matrix_rank(a))

2
