# **Code for various Vector Operations**

## **1.Vector Dot Product**

In [3]:
import numpy as np

In [9]:
# Pythonic code
quantity=[3,5,2]
price=[10,20,30]  
def dot(a,b):
    result=0
    for i,j in zip(a,b):
        result+=i*j
    return result

result=dot(quantity,price)
print(f"Result of dot product is:{result}")



Result of dot product is:190


In [11]:
# Vectorised Operation Numpy
import numpy as np
quantity=np.array([3,5,2])
price=np.array([10,20,30])  
print(f"Result of dot product is:{np.dot(quantity,price)}")


Result of dot product is:190


## **2.Vector Scalar Multiplication**

In [1]:
# Pythonic version
v1=[10,20,30]
scalar=8    
for i in range(len(v1)):
    v1[i]=scalar*v1[i]

print(f"Vector after scalar multiplication:{v1}")

Vector after scalar multiplication:[80, 160, 240]


In [5]:
# Numpy Version
v1=np.array([10,20,30])
print(f"Vector after scalar multiplication:{8*v1}")

Vector after scalar multiplication:[ 80 160 240]


## **3.Vector Addition Subtraction**



In [6]:
#Pythonic way
v1=[1,2,4]
v2=[1,4,5]
v3=[]
for i,j in zip(v1,v2):
    v3.append(i-j)
print(f"Vector Addition:{v3}")

Vector Addition:[0, -2, -1]


In [7]:
# numpy way
v1=np.array([1,2,4])
v2=np.array([1,4,5])
print(v1-v2)

[ 0 -2 -1]


## **4.Vector Multiplicaton**

In [10]:
# Numpy method:
v1=np.array([[1,3],[4,5]])
v2=np.array([[1,3,4],[4,5,6]])
v3=v1@v2
print(v3)

[[13 18 22]
 [24 37 46]]


## **5.Vector Cross Product**


In [12]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
v3=np.cross(v1,v2)
print(v3)

[-3  6 -3]


## **6.Cosine Similarity**


In [ ]:
# Numpy method
def cosine_similarity(a,b):
    v1=np.array(a)
    v2=np.array(b)
    similarity_score=(np.dot(v1,v2))/(np.linalg.norm(v1)*np.linalg.norm(v2))
    return similarity_score
a=[float(x) for x in input("Enter a vector").split(',')]
b=[float(x) for x in input("Enter a vector").split(',')]
print(f"Cosine Similarity between {a} and {b}:{cosine_similarity(a,b)}")

Cosine Similarity between [0.29, 0.68] and [0.51, 0.71]:0.9759425005795868
