# **<span style="color:orange">Assignment-1</span>**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
v1=np.zeros(10).astype('int')
v1[4]=1
v1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
#Code here
a=int(input("Enter value of a:"))
b=int(input("Enter value of b:"))
v2=np.random.randint(1,100,size=(a,b))
v2_avg=v2.mean()
print(v2)
print(v2_avg)

Enter value of a:3
Enter value of b:2
[[37 26]
 [60 82]
 [34 80]]
53.166666666666664


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [17]:
#Code here
a=int(input("Enter value of a:"))
b=int(input("Enter value of b:"))
v3=np.zeros((a,b)).astype('int')
print("Original array:\n",v3)
for i in (0,v3.shape[0]-1):
  for j in range(v3.shape[1]):
    v3[i][j]=1

for i in (0,v3.shape[1]-1):
  for j in range(v3.shape[0]):
    v3[j][i]=1

print("Modified array:\n",v3)



Enter value of a:4
Enter value of b:5
Original array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Modified array:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [26]:
#Code here
v4=np.random.rand(10)
print(v4)

[0.87494784 0.39769508 0.2604046  0.52431057 0.70155866 0.56468815
 0.88341822 0.13978496 0.8585273  0.64925096]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [31]:
#Code here
v5=np.eye(3,4)
print(v5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [35]:
#Code here
v6=np.random.randint(0,high=4,size=(5,5))
print(v6)

[[3 1 3 0 0]
 [1 2 2 0 1]
 [3 2 0 1 0]
 [2 2 0 0 2]
 [1 0 2 2 3]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [46]:
#code here
point=np.array([2,3])
array_points=np.random.randint(1,high=100,size=(10,2))
print(array_points)
print()
diff=array_points-point
print(diff)
print()
sqr=diff*diff
print(sqr)
dist=[]
for i in sqr:
  distance=np.sqrt(i[0]+i[1]).astype('int')
  dist.append(distance)

print()
print(dist)



[[68 10]
 [10 85]
 [29  3]
 [76 47]
 [ 2 34]
 [97 41]
 [49 86]
 [ 7 37]
 [92 55]
 [96 72]]

[[66  7]
 [ 8 82]
 [27  0]
 [74 44]
 [ 0 31]
 [95 38]
 [47 83]
 [ 5 34]
 [90 52]
 [94 69]]

[[4356   49]
 [  64 6724]
 [ 729    0]
 [5476 1936]
 [   0  961]
 [9025 1444]
 [2209 6889]
 [  25 1156]
 [8100 2704]
 [8836 4761]]

[np.int64(66), np.int64(82), np.int64(27), np.int64(86), np.int64(31), np.int64(102), np.int64(95), np.int64(34), np.int64(103), np.int64(116)]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [55]:
#Code here
a=np.arange(1,337).reshape(6,7,8)
print(a)
print()
print(a[1][5][3])

[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [64]:
#Code here
l="1 2 3 4 -8 -10"
nums=[int(x) for x in l.split(' ')]
nums=nums[::-1]
narray=np.array(nums).astype('float32')
print(narray)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [67]:
#Code here
a=np.arange(1,17).reshape(2,8)
print(a.size)


16


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [73]:
#Code here
def softmax(input):
  e=np.exp(input)
  e_sum=e.sum()
  return e/e_sum

result=softmax([33.17344305, 45.61961654,82.05405781 ,80.9647098 , 68.82830233, 91.52064278])
print(result)

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [75]:
#Coder here
a=np.arange(0,10).reshape(2,5)
b=np.arange(1,11).reshape(2,5)

result=np.vstack((a,b))
print(result)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [76]:
#Code here
start_date='2020-11-25'
end_date='2020-11-30'
start=np.datetime64(start_date)
end=np.datetime64(end_date)
def date_array(start,end):
  return np.arange(start,end+1,dtype='datetime64[D]')
d=date_array(start,end)
print(d)

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [85]:
#code here
a=np.arange(1,25).reshape(4,6).astype('float32')
print(a)
for i in range(a.shape[0]):
  mean=a[i].mean()
  a[i]=a[i]-mean
print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]]
3.5
9.5
15.5
21.5
[[-2.5 -1.5 -0.5  0.5  1.5  2.5]
 [-2.5 -1.5 -0.5  0.5  1.5  2.5]
 [-2.5 -1.5 -0.5  0.5  1.5  2.5]
 [-2.5 -1.5 -0.5  0.5  1.5  2.5]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [92]:
#Code here
a=np.arange(1,25).reshape(6,4)
print("Original array:\n", a)

# To swap rows 0 and 1 (this was the intention of the buggy code, but Q-15 asks for columns):
# The previous code had a bug because 'temp = a[0]' created a view, not a copy.
# When 'a[0] = a[1]' was executed, a[0] (and thus temp) changed before temp was assigned to a[1].
# Correct way to swap rows 0 and 1:
# temp = a[0].copy()
# a[0] = a[1]
# a[1] = temp
# print("\nArray after swapping rows 0 and 1 (fixed logic):\n", a)

# As per Q-15: Swap column-1 with column-2 (0-indexed, so column at index 0 and 1)
a[:, [0, 1]] = a[:, [1, 0]]

print("\nArray after swapping column-0 and column-1 (as per Q-15):\n", a)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Array after swapping column-0 and column-1 (as per Q-15):
 [[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]
 [14 13 15 16]
 [18 17 19 20]
 [22 21 23 24]]


In [98]:
print(a[:,[1,0]])
print(a[:,[0,1]])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 2  1]
 [ 6  5]
 [10  9]
 [14 13]
 [18 17]
 [22 21]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [99]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=np.maximum(a,b)
print(c)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [100]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3054, 7419, 8664, 2863, 6554],
       [4999, 2453, 1947, 9745, 5494],
       [6162, 3163, 9484, 3166,  345],
       [7495, 6127, 9229, 7876, 9281],
       [8302, 1060, 4038,  857, 5790],
       [4492, 5738, 4197, 1342,  646],
       [3044, 2831, 9882, 2102,  518],
       [1449, 1334, 3738, 8795, 1030]])

In [101]:
#Code here
def normalise(arr):
  arr_min=arr.min()
  arr_max=arr.max()
  return (arr-arr_min)/(arr_max-arr_min)

print(normalise(arr1))

[[0.28405159 0.74174269 0.87228688 0.26402433 0.65104331]
 [0.48799413 0.22103387 0.16797735 0.9856349  0.53989724]
 [0.60994023 0.29548076 0.9582678  0.29579532 0.        ]
 [0.74971165 0.60627032 0.93152983 0.78966132 0.93698228]
 [0.83432945 0.07497116 0.38722869 0.05368565 0.57093426]
 [0.43483276 0.56548181 0.4039006  0.10454021 0.03156129]
 [0.28300304 0.26066897 1.         0.18422984 0.01813988]
 [0.11575967 0.10370137 0.35577226 0.88602286 0.07182552]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [104]:
#Code here
def nth_largest(arr,n):
  arr.sort()
  return arr[-n]

arr=[12,34,40,7,1,0]
print(nth_largest(arr,3))

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [109]:
#code here
a = np.array([1,2,3])
b=np.repeat(a,3)
print(b)
c=np.tile(a,3)
print(c)
d=np.concatenate((b,c))
print(d)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
