# **<span style="color:orange">Indexing in Python</span>**

## **Basic Indexing**
- used for accessing elements in an array
- slicing operation
```python
arr[index]
arr[start:stop:step]
```

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [2]:
arr[1:4] = 99
print(arr)

[10 99 99 99 50]


## **Fancy Indexing**

- Selecting elements using index arrays
```python
arr[[i1,i2,i3]]
```

In [4]:
print(arr[[0,4]])

[10 50]


## **Boolean Indexing**
- Selecting elements using true False condition

```python
arr[condition]
```

In [6]:
mask=arr[arr>30]
mask

array([99, 99, 99, 50])

In [7]:
arr=np.arange(1,21)
arr[(arr%2==0) & (arr%3==0)]=0
print(arr)

[ 1  2  3  4  5  0  7  8  9 10 11  0 13 14 15 16 17  0 19 20]
