## Numpy Basics

### 1. Numpy Arrays

In [17]:
import numpy as np
from time import time

## Vectorisation and Vectorised Operation in Numpy and it's Performance benefits:

### Non Vectorised Array Addition

In [20]:
n=1000000
a=np.random.rand(n)
b=np.random.rand(n)
c=[]
start_time=time()
for k in range(n):
    c.append(a[k]+b[k])

end_time=time()
total_time_1=end_time-start_time
print(f"Time taken for entire operation:{total_time_1}")


Time taken for entire operation:0.5075476169586182


### Vectorised Operation of Array Addition

In [21]:
start_time=time()
d=a+b
end_time=time()
total_time_2=end_time-start_time
print(f"Time taken for entire operation:{total_time_2}")

Time taken for entire operation:0.00528264045715332


In [13]:
print(c==d)

[ True  True  True ...  True  True  True]


In [22]:
# Increase in Performance to vectorised operaion
print(f"Performance increased by:{total_time_1/total_time_2} times")

Performance increased by:96.07839508958794 times


In [13]:
n1=np.array([1,2,3,4])
n2=np.array([8,3])
print(n1,type(n1),sep='\t')
print(n2,type(n2),sep='\t')
print(n1**2)
print(n1.dtype)
print(n2.dtype)

[1 2 3 4]	<class 'numpy.ndarray'>
[8 3]	<class 'numpy.ndarray'>
[ 1  4  9 16]
int64
int64


- This code demonstrates how slicing a numpy array does create a copy of instead create a view of the original array with adjusted shape and stride

In [23]:
arr=np.array([1,2,3,4,5])
new_arr=arr[:4] # does not create of slice list only create a view to original array
print(f"Old array:{arr}")
print(f"New Array:{new_arr}")
new_arr[0]=99 # changes original arr also
print(f"Old array:{arr}")
print(f"New Array:{new_arr}")
print(f"ID of arr:{id(arr)}")
print(f"ID of new_arr:{id(new_arr)}")
print(f"ID of arr[0]:{id(arr[0])}") # Share same memory buffer
print(f"ID of new_arr[1]:{id(new_arr[0])}")
print(arr is new_arr)


Old array:[1 2 3 4 5]
New Array:[1 2 3 4]
Old array:[99  2  3  4  5]
New Array:[99  2  3  4]
ID of arr:2688046637936
ID of new_arr:2688046638128
ID of arr[0]:2688024904912
ID of new_arr[1]:2688024904912
False


- To prevent this windowing of same memory buffer we can forcefully create a copy using copy() method

In [24]:
arr=np.array([1,2,3,4,5])
new_arr=arr[:4].copy() #  slice the list and create a separate copy of slice list
print(f"Old array:{arr}")
print(f"New Array:{new_arr}")
new_arr[0]=99 # does not change original array
print(f"Old array:{arr}")
print(f"New Array:{new_arr}")
print(f"ID of arr:{id(arr)}")
print(f"ID of new_arr:{id(new_arr)}")
print(f"ID of arr[0]:{id(arr[0])}") # Share same memory buffer
print(f"ID of new_arr[0]:{id(new_arr[0])}")
print(arr is new_arr)

Old array:[1 2 3 4 5]
New Array:[1 2 3 4]
Old array:[1 2 3 4 5]
New Array:[99  2  3  4]
ID of arr:2688046638416
ID of new_arr:2688046638608
ID of arr[0]:2688024904560
ID of new_arr[0]:2688024904560
False


In [29]:
print("Memory address of arr:", arr.__array_interface__['data'])
print("Memory address of new_arr:", new_arr.__array_interface__['data'])


Memory address of arr: (1859973347632, False)
Memory address of new_arr: (1859968143104, False)


## Numpy Performance efficiency

In [30]:
import numpy as np
import time

# Python list
L = list(range(1000000))
start = time.time()
[x**2 for x in L]
print("List time:", time.time() - start)

# NumPy array
A = np.arange(1000000)
start = time.time()
A**2
print("NumPy time:", time.time() - start)

List time: 0.13486552238464355
NumPy time: 0.0032215118408203125


## Memory Efficiency

In [31]:
import sys
L = list(range(10))
A = np.arange(10)

print("List size:", sys.getsizeof(L))
print("NumPy array size:", A.nbytes)


List size: 136
NumPy array size: 80


## Vectorised Operation

In [32]:
# List
a=[x+5 for x in L]
print(a)
# NumPy
b=A + 5   # way faster
print(b)


[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[ 5  6  7  8  9 10 11 12 13 14]


## Broadcasting

In [33]:
A = np.array([1,2,3])
B = np.array([10])
print(A + B)  # [11, 12, 13]


[11 12 13]
