## Ways to Declare Numpy Array

1. From existing data (lists,tuple,other array)

In [1]:
import numpy as np

In [8]:
arr1=np.array([1,2,3,44,42]) # 1D array
arr2=np.array([[1,2],[3,4]]) # 2D array
arr3=np.array((((1,2,3),(4,5,6),(7,8,9)),((1,2,3),(4,5,6),(7,8,9)))) # 3D array
print(arr1,arr1.shape)
print(arr2,arr2.shape)
print(arr3,arr3.shape)

[ 1  2  3 44 42] (5,)
[[1 2]
 [3 4]] (2, 2)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] (2, 3, 3)


In [16]:
arr4=np.asarray(arr1) # doesn't copy array if it exist refer to same ndarray
arr5=np.array(arr1) # copy array even if it exist
arr5[1]=99
arr4[0]=87
print(arr4)
print(arr1)
print(arr5)

[87  2  3 44 42]
[87  2  3 44 42]
[87 99  3 44 42]


## 2. Based on Shape

In [21]:
arr6=np.zeros(5)
print(arr6)
arr7=np.zeros((2,4),dtype=int)
print(arr7)

[0. 0. 0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [22]:
arr8=np.ones(5)
print(arr8)
arr9=np.ones((2,4),dtype=int)
print(arr9)

[1. 1. 1. 1. 1.]
[[1 1 1 1]
 [1 1 1 1]]


In [23]:
arr10=np.full((2,3), 7)             # 2x3 filled with 7
print(arr10)

[[7 7 7]
 [7 7 7]]


In [24]:
arr11=np.empty((2,2))
print(arr11)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [31]:
arr12=np.eye(3)
arr13=np.eye(2,4,-1) # np.eye(row,col,conse triangle pe 1 chaiye)
print(arr12)
print(arr13)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [36]:
arr14=np.identity(3,dtype=int)
print(arr14) # 3x3 Identity matrix

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 3. Based on Sequences

In [ ]:
arr15=np.arange(1,11,2) # np.arange(start,stop(exclusive),step)
print(arr15)

[1 3 5 7 9]


In [39]:
arr16=np.linspace(0, 1, 5)  # [0.   0.25 0.5  0.75 1. ]
print(arr16)

[0.   0.25 0.5  0.75 1.  ]


In [43]:
arr17=np.logspace(1, 4, 4,base=10)  # [10. 100. 1000. 10000.]
print(arr17)

[   10.   100.  1000. 10000.]


## 4. Random Values


In [ ]:
# Uniform Distribution
arr18=np.random.rand(3,2)  # random floats in [0,1)
print(arr18)

[[0.28241416 0.75603574]
 [0.17408836 0.36115504]
 [0.45217326 0.82634099]]


In [47]:
# Normal Distribution
arr19=np.random.randn(3)        # 3 values from standard normal (mean=0, std=1)
print(arr19)

[0.33504062 0.31751119 0.22858903]


In [48]:
# Random integers
arr20=np.random.randint(0, 10, (2,3))  # 2x3 random ints in [0,10)
print(arr20)

[[4 2 1]
 [9 0 9]]


In [49]:
# Random Choice
arr21=np.random.choice([1, 2, 3, 4], size=5)   # Random picks from list
print(arr21)

[2 1 4 4 3]


In [52]:
# Random uniform/normal with parameters
arr22=np.random.uniform(5, 10, size=(2,3))     # Between 5 and 10
arr23=np.random.normal(50, 10, size=5)         # Mean=50, std=10
print(arr22,arr23,sep='\n')

[[6.13156047 6.66455911 9.3581738 ]
 [8.4351126  9.68699589 5.49544867]]
[68.0780041  30.00361043 51.08269219 37.35131867 54.5203427 ]


## 5. Copying and Reshaping

In [54]:
arr = np.array([1,2,3])
arr_copy = np.copy(arr)
print(arr_copy)


[1 2 3]


In [55]:
np.arange(12).reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
np.tile([1,2], (3,3))   # Repeat [1,2] → 3x2


array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

In [59]:
np.repeat([1,2,3], 2)   # [1 1 2 2 3 3]


array([1, 1, 2, 2, 3, 3])

## Telling data-type of values while declaring

In [60]:
a2=np.array([1,2,3],dtype=float)
a3=np.array(a2,dtype=bool)
a4=np.array(a2,dtype=complex)
print(a3)
print(a4)
print(a2)

[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]
[1. 2. 3.]
