## Concatenate Operation

In [5]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b),axis=0)


print(c)   # [1 2 3 4 5 6]



[1 2 3 4 5 6]


In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(np.concatenate((a,b), axis=0)) # Row wise

# [[1 2]
#  [3 4]
#  [5 6]]


[[1 2]
 [3 4]
 [5 6]]


In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b), axis=1)) # column wise
print(np. concatenate((a,b),axis=0)) # row wise
# [[1 2 5 6]
#  [3 4 7 8]]


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6,7]])
np.concatenate((a,b), axis=1)  # ValueError


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## H-Stack

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.hstack((a,b)))
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
print(np.hstack((c,d)))
print(np.concatenate((c,d),axis=1))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## V-Stack

In [15]:
print(np.vstack((a,b)))
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [4 5 6]]


AxisError: axis 1 is out of bounds for array of dimension 1

In [17]:
print(np.vstack((c,d)))
print(np.concatenate((c,d),axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Split

In [18]:
arr1=np.array([1,2,3,4,5,6])
print(np.split(arr1,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [19]:
print(np.split(arr1,[1,4]))

[array([1]), array([2, 3, 4]), array([5, 6])]


In [21]:
arr2=np.random.rand(4,4)
print(arr2)

[[0.45611967 0.29996342 0.62853035 0.62733209]
 [0.7673439  0.83232376 0.78568177 0.03348315]
 [0.77860618 0.62094379 0.43095573 0.28365792]
 [0.73342789 0.41012272 0.50505871 0.93454145]]


In [28]:
print(np.split(arr2,2,axis=0)) #vsplit

print()
print(np.vsplit(arr2,2))

[array([[0.45611967, 0.29996342, 0.62853035, 0.62733209],
       [0.7673439 , 0.83232376, 0.78568177, 0.03348315]]), array([[0.77860618, 0.62094379, 0.43095573, 0.28365792],
       [0.73342789, 0.41012272, 0.50505871, 0.93454145]])]

[array([[0.45611967, 0.29996342, 0.62853035, 0.62733209],
       [0.7673439 , 0.83232376, 0.78568177, 0.03348315]]), array([[0.77860618, 0.62094379, 0.43095573, 0.28365792],
       [0.73342789, 0.41012272, 0.50505871, 0.93454145]])]


In [29]:
print(np.split(arr2,2,axis=1)) #hsplit

[array([[0.45611967, 0.29996342],
       [0.7673439 , 0.83232376],
       [0.77860618, 0.62094379],
       [0.73342789, 0.41012272]]), array([[0.62853035, 0.62733209],
       [0.78568177, 0.03348315],
       [0.43095573, 0.28365792],
       [0.50505871, 0.93454145]])]


In [30]:
print(np.hsplit(arr2,2))

[array([[0.45611967, 0.29996342],
       [0.7673439 , 0.83232376],
       [0.77860618, 0.62094379],
       [0.73342789, 0.41012272]]), array([[0.62853035, 0.62733209],
       [0.78568177, 0.03348315],
       [0.43095573, 0.28365792],
       [0.50505871, 0.93454145]])]
