## Array and Vectorise Operations

1. Elementwise Arithmetic Operations

In [2]:
import numpy as np

In [8]:
a1=np.arange(1,13)
a2=np.arange(13,25)
print(a1)
print(a2)
add=a1+a2
sub=a1-a2
product=a1*a2
div=a1/a2
mod=a1%a2
floordiv=a1//a2
exp=a1**a2
print(add)
print(sub)
print(product)
print(div)
print(mod)
print(floordiv)
print(exp)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15 16 17 18 19 20 21 22 23 24]
[14 16 18 20 22 24 26 28 30 32 34 36]
[-12 -12 -12 -12 -12 -12 -12 -12 -12 -12 -12 -12]
[ 13  28  45  64  85 108 133 160 189 220 253 288]
[0.07692308 0.14285714 0.2        0.25       0.29411765 0.33333333
 0.36842105 0.4        0.42857143 0.45454545 0.47826087 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 0 0 0 0 0 0 0 0 0 0 0]
[                   1                16384             14348907
           4294967296         762939453125      101559956668416
    11398895185373143  1152921504606846976 -1261475310744950487
  1864712049423024128  6839173302027254275 -5124814900970913792]


In [ ]:
a3=np.array([1]) # here broadcasting rule is applied  since a3 is of shape (1,)
# Broadcasting fail if a3 shape is not equal to (1,)
print(a3.shape)
z=a1+a3 # a3=[1 1 1 1 1 1 1 1 1 1 1 1] after broadcasting
print(z)

(1,)
[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([1,2,3]) # b=[[1,2,3],[1,2,3]] after broadcasting
# broadcasting is true if no. of rows of 1D array no. of rows of 2D array
print(b.shape)
print(a + b)
# [[2 4 6]
#  [5 7 9]]


(2, 3)
(3,)
[[2 4 6]
 [5 7 9]]


- Note:Arithmetic operators require both arrays to have the same shape OR be broadcast-compatible according to broadcasting rules.

---
2.  Comparison Operations

In [15]:
print(a1>a2)
print(a1<a2)
print(a1==a2)
print(a1!=a2)
print(a1>=a2)
print(a1<=a2)

[False False False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True]


In [17]:
# Use case:Use for filtering
print(a1[a1>2]) # boolean indexing

[ 3  4  5  6  7  8  9 10 11 12]


---
3. Logical Operations

In [21]:
np.logical_and([True,False,True],[1,3,0])


array([ True, False, False])

In [22]:
np.logical_or([True,False,True],[1,3,0])

array([ True,  True,  True])

In [23]:
np.logical_not([True,False,True])

array([False,  True, False])

In [24]:
np.logical_xor([True,False,True],[1,3,0])

array([False,  True,  True])

---
4. Aggregate Operations

In [11]:
a1.sum(axis=0) #  wise sum since axis=0 since 1D array


np.int64(78)

In [ ]:
a1

In [34]:
a1.reshape(12,-1).sum(axis=None)

np.int64(78)

In [35]:
a1.max()

np.int64(12)

In [36]:
a1.min()

np.int64(1)

In [37]:
a1.mean()

np.float64(6.5)

In [38]:
a1.std()

np.float64(3.452052529534663)

In [40]:
a1.var()

np.float64(11.916666666666666)

In [ ]:
a1.prod() #= 12!

np.int64(479001600)

In [ ]:
m = np.array([[1,2,3],[4,5,6]])
print(m)
print(m.sum())        # 21
print(m.sum(axis=0))  # [5 7 9] (column sums)
print(m.sum(axis=1))  # [6 15] (row sums)
print(m.mean(axis=1)) # [2. 5.] (row means)


[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[2. 5.]



---

### Your code:

```python
import numpy as np
a1 = np.arange(1,13)   # 1D array [1,2,...,12]
print(a1.sum(axis=0))
```

👉 Output:

```
78
```

---

# 🔹 Why not `[1 2 3 ... 12]`?

Because:

* `a1` is **1D** (shape `(12,)`).
* When you call `.sum(axis=0)` on a 1D array, **axis=0 is the only axis**.
* NumPy reduces that axis → sums all 12 elements → gives a **scalar** (`78`).

So you don’t get back the same array, you get the total sum.

---

# 🔹 When would you get elementwise-like results?

You might be expecting **row-wise or column-wise sums**, which only make sense in **2D (or higher)** arrays.

Example:

```python
a2 = np.arange(1,13).reshape(3,4)
print(a2)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

print(a2.sum(axis=0))   # column sums
# [15 18 21 24]

print(a2.sum(axis=1))   # row sums
# [10 26 42]
```

---

# 🔹 How to get back `[1 2 3 ... 12]`?

If your intent is *not to reduce (sum)* but just return the array as-is, don’t use `.sum()`.

```python
a1 = np.arange(1,13)
print(a1)   # [ 1  2  3  4  5  6  7  8  9 10 11 12]
```

If you actually wanted a **cumulative sum** (running total):

```python
print(a1.cumsum())
# [  1   3   6  10  15  21  28  36  45  55  66  78]
```

---

✅ **Summary**

* `sum(axis=0)` on 1D array = total sum.
* For `[1,2,3,...,12]` → just the array itself.
* For running totals → use `.cumsum()`.
* For row/col sums → reshape to 2D, then use `axis=0/1`.

---

👉 Do you want me to make a **cheat sheet of reduction ops (`sum`, `mean`, `cumsum`, `prod`, `cumprod`, etc.) with axis behavior in 1D vs 2D**? That would help avoid this kind of mix-up.


---
5. Linear Algebra Operations

In [48]:
np.dot(a1,a2)

np.int64(1586)

In [ ]:
# Dot Product
a=np.array((1,2,2))
b=np.array((4,3,2))
# Both arrays shape should be same
print(np.dot(a,b)) # 1*4 + 3*2 +2*2=14

14


In [55]:
# Matrix Multiplication
a1=np.array([[1,2],[4,2],[5,3]])
print(a1.shape)
a2=np.array([[1,2,4],[4,2,5]])
print(a2.shape)
print(np.matmul(a1,a2))
print(a1@a2) # same as matmul

(3, 2)
(2, 3)
[[ 9  6 14]
 [12 12 26]
 [17 16 35]]
[[ 9  6 14]
 [12 12 26]
 [17 16 35]]


In [58]:
# Cross Multiplication
a=np.array((1,2,2))
b=np.array((4,3,2))
# Both arrays shape should be same
c=np.cross(a,b)
print(c) # Output is a vector/ndarray
print(type(c))

[-2  6 -5]
<class 'numpy.ndarray'>


In [60]:
# Inverse of a Matrix
np.linalg.inv(np.array([[1,2],[3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
# Determinant of Matrix
np.linalg.det(np.array([[1,2],[3,4]]))

np.float64(-2.0000000000000004)

In [62]:
# Eigenvalues,eigenvector
np.linalg.eig(np.array([[1,2],[3,4]]))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [4]:
x=np.array([[1,2,3],[4,5,6]])
print(x.sum(axis=0))
print(x.sum(axis=1))

[5 7 9]
[ 6 15]


## Universal Functions

In [18]:
arr = np.array([1,4,9])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[0.         1.38629436 2.19722458]
[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]


## Cummulative Operations

In [20]:
arr = np.array([1,2,3,4])
print(np.cumsum(arr,axis=None))
print(np.cumprod(arr,axis=None))

[ 1  3  6 10]
[ 1  2  6 24]


## Clipping and Rounding

In [25]:
arr=np.random.rand(4)*4
print(arr)
print(np.clip(arr,1,3)) 
print(np.round(arr,2))
print(np.floor(arr))
print(np.ceil(arr))

[2.93412388 0.12541869 3.97189023 0.18630198]
[2.93412388 1.         3.         1.        ]
[2.93 0.13 3.97 0.19]
[2. 0. 3. 0.]
[3. 1. 4. 1.]
