## Indexing in Numpy

1. Simple Indexing

In [1]:
import numpy as np

In [3]:
arr=np.round((np.random.rand(6)*6),2)
print(arr)
print(arr[0])
for x in range(6):
    print(arr[x])

[4.75 3.35 2.23 5.01 0.5  5.89]
4.75
4.75
3.35
2.23
5.01
0.5
5.89


2. Negative Indexing

In [5]:
print(arr)
print(arr[-5])

for x in range(-1,-7,-1):
    print(arr[x])

[4.75 3.35 2.23 5.01 0.5  5.89]
3.35
5.89
0.5
5.01
2.23
3.35
4.75


3. Logical Indexing: Used for filtering

In [6]:
print(arr)
print(arr[arr>4])

[4.75 3.35 2.23 5.01 0.5  5.89]
[4.75 5.01 5.89]


4. Fancy Indexing

In [7]:
print(arr)
print(arr[[0,3,5]])

[4.75 3.35 2.23 5.01 0.5  5.89]
[4.75 5.01 5.89]


---
---
## Slicing in Numpy

1. 1-D Slicing

In [ ]:
arr=np.round((np.random.rand(10)*10),2)
print(arr)

print(arr[::])
print(arr[::-1]) # start: at index:-1/len(arr)-1  stop: at index -len(arr)-1/0
print(arr[::-2])
print(arr[-2:-9:-1])
print(arr[-1:-11:-1]) #print(arr[::-1]) 
print(arr[0:10:1]) #print(arr[::])

[5.88 3.11 8.52 2.41 5.14 3.88 0.25 7.37 3.81 2.04]
[5.88 3.11 8.52 2.41 5.14 3.88 0.25 7.37 3.81 2.04]
[2.04 3.81 7.37 0.25 3.88 5.14 2.41 8.52 3.11 5.88]
[2.04 7.37 3.88 2.41 3.11]
[3.81 7.37 0.25 3.88 5.14 2.41 8.52]
[2.04 3.81 7.37 0.25 3.88 5.14 2.41 8.52 3.11 5.88]
[5.88 3.11 8.52 2.41 5.14 3.88 0.25 7.37 3.81 2.04]


2. 2-D Slicing
arr[row slice][col slic]

In [ ]:
arr=np.round((np.random.rand(5,5)*10),2)
print(arr)
print(arr[::][::])
print(arr[::-1][::])
print(arr[::][::-1]) # sequential evaluation

[[6.98 2.38 4.63 6.07 3.2 ]
 [6.34 3.38 6.43 0.96 8.95]
 [0.53 9.96 5.73 0.37 5.32]
 [8.99 7.07 9.6  7.39 2.45]
 [8.   1.44 5.37 3.37 6.93]]
[[6.98 2.38 4.63 6.07 3.2 ]
 [6.34 3.38 6.43 0.96 8.95]
 [0.53 9.96 5.73 0.37 5.32]
 [8.99 7.07 9.6  7.39 2.45]
 [8.   1.44 5.37 3.37 6.93]]
[[8.   1.44 5.37 3.37 6.93]
 [8.99 7.07 9.6  7.39 2.45]
 [0.53 9.96 5.73 0.37 5.32]
 [6.34 3.38 6.43 0.96 8.95]
 [6.98 2.38 4.63 6.07 3.2 ]]
[[8.   1.44 5.37 3.37 6.93]
 [8.99 7.07 9.6  7.39 2.45]
 [0.53 9.96 5.73 0.37 5.32]
 [6.34 3.38 6.43 0.96 8.95]
 [6.98 2.38 4.63 6.07 3.2 ]]


In [ ]:
print(arr)
print(arr[::,::-1]) # simultaneous slicing
print(arr[:3,2:4])

[[6.98 2.38 4.63 6.07 3.2 ]
 [6.34 3.38 6.43 0.96 8.95]
 [0.53 9.96 5.73 0.37 5.32]
 [8.99 7.07 9.6  7.39 2.45]
 [8.   1.44 5.37 3.37 6.93]]
[[3.2  6.07 4.63 2.38 6.98]
 [8.95 0.96 6.43 3.38 6.34]
 [5.32 0.37 5.73 9.96 0.53]
 [2.45 7.39 9.6  7.07 8.99]
 [6.93 3.37 5.37 1.44 8.  ]]


In [20]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[::][::-1])
print()
print(arr1[1:2,:3:2])

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[4 6]]


In [21]:
a3 = np.arange(27).reshape(3,3,3)

In [22]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
a3.ravel() # flatterns an array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [24]:
a3.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [25]:
for x in np.nditer(a3):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
